# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a68d52935994f5da2289e09644c30721ee19f77a7e184aed96a43da070a084468ba8aa46b8595fe15768c6e189db07095d7ea9dd89376d6f338f95621e074ad8

test:
  secret_key_base: 158418dc31471185d0b621aecfd376e0eb0b1cc006201fb9509f3af7ad45d20f5bdb2925dd002d79ffc5132703af877ec9dbdc05e9c2e740a77ed89f0d1ada63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
